apiVersion: v2
name: central-auth-server
description: Helm chart for the Centralized OAuth2 Authorization Server
type: application
version: 1.0.0
appVersion: "0.0.1-SNAPSHOT" # Mismo valor que en tu pom.xml