apiVersion: v1
kind: Secret
metadata:
  name: {{ include "central-auth-server.fullname" . }}-db-secret
  labels:
    {{- include "central-auth-server.labels" . | nindent 4 }}
type: Opaque
data:
  # Helm will automatically encode these to Base64 during deployment
  db-password: {{ .Values.database.password | b64enc | quote }}
  db-username: {{ .Values.database.username | b64enc | quote }}