apiVersion: v1
kind: Service
metadata:
  name: {{ include "central-auth-server.fullname" . }}
  labels:
    {{- include "central-auth-server.labels" . | nindent 4 }}
spec:
  # Para Kind, usaremos NodePort para exponerlo hacia Windows
  type: {{ .Values.service.type | default "NodePort" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      protocol: TCP
      name: http
      # Este puerto debe coincidir con el 'containerPort' que definimos en el kind-config.yaml
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 30000
      {{- end }}
  selector:
    {{- include "central-auth-server.selectorLabels" . | nindent 4 }}